# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: adam bezemek
email: adam.bezemek@gmail.com
description: >- # this means to ignore newlines
  Adam Bezemek is a front-end architect, speaker, cultural ambassador, loving father, and boyfriend; living in the beautiful bluffs of La Crosse, WI.
intro: >- # this means to ignore newlines
  i'm <a href="/about-me/" class="link-primary">adam bezemek</a>, a front-end architect, speaker, cultural ambassador, loving father, and boyfriend; living in the beautiful bluffs of la crosse, wi.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
social_link: twitter
social_username: adambezemek

twitter_username: adambezemek
github_username:  adambezemek

# Build settings
markdown: kramdown
theme: jekyll-swiss

sass:
    sass_dir: _sass
    # style: compressed
    
plugins:
  - jekyll-feed

include: ["_pages"] 
permalink: /:title/ 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
